# Generated by Django 5.0.1 on 2024-01-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_alter_studentcoursemapping_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentfacultymapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facultyname', models.CharField(max_length=50)),
                ('facultyid', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'studentfacultymapping_table',
            },
        ),
    ]
